### PR TITLE
fix: do not allow importing dev deps from lib/bin

### PR DESCRIPTION
**Pull request by tjenkinson**
## References
Refs https://github.com/npm/template-oss/pull/316
Needed by https://github.com/npm/node-semver/pull/559

### CODE REVIEW

**Comment by wraithgar** [comment]
Now we're talking.  Tested this in a local branch

```sh
$ npm run lint

> ssri@10.0.2 lint
> eslint "**/*.js"


/Users/wraithgar/Development/npm/ssri/branches/main/lib/index.js
  3:13  error  'tap' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

✖ 1 problem (1 error, 0 warnings)
```

**Comment by wraithgar** [comment]
Gonna give @lukekarrys a few days to weigh in since he's done more work on these rules than I have.

**Review by lukekarrys — APPROVED** [review]

**Comment by wraithgar** [comment]
Need to do some housekeeping on this repo before we can publish.

The irony is we'll have to work *around* this rule in node-semver since it has an exception to having its code in `./lib`.

This was still the right choice because we really want to centrally manage this opinion across our 80+ repos, not just piecemeal it.

**Comment by wraithgar** [comment]
we opted not to change `node-semver` cause it was deemed a disruptive semver major change.

**Pull request merged**
